#  ------------------------------  Stock USA  ------------------------------

## No4 Stock USA import data 12-4-2020

In [72]:
import talib as ta
import yfinance as yf
stock = 'V'
aapl = yf.download(stock, '2010-1-1', '2020-4-10')

[*********************100%***********************]  1 of 1 completed

In [76]:
aapl.head(25)

                 Open       High        Low      Close  Adj Close    Volume
Date
2009-12-31  21.995001  22.045000  21.792500  21.865000  17.992781  12643600
2010-01-04  22.000000  22.192499  21.865000  22.035000  18.132669  20180000
2010-01-05  21.825001  21.882500  21.500000  21.782499  17.924887  25833600
2010-01-06  21.752501  21.770000  21.475000  21.490000  17.684185  16254000
2010-01-07  21.492500  21.750000  21.387501  21.690001  17.848776  27841200
2010-01-08  21.705000  21.847500  21.557501  21.750000  17.898142  11907200
2010-01-11  21.877501  21.985001  21.542500  21.687500  17.846712  12912000
2010-01-12  21.645000  21.762501  21.462500  21.584999  17.762367  12842000
2010-01-13  21.615000  21.799999  21.487499  21.785000  17.926945  13428800
2010-01-14  21.742500  21.882500  21.625000  21.860001  17.988657  18379600
2010-01-15  21.870001  21.885000  21.480000  21.535000  17.721218  21295200
2010-01-19  21.542500  22.102501  21.424999  21.962500  18.073015  15239600
2010-01-20  21.920000  21.934999  21.577499  21.855000  17.984547  12771200
2010-01-21  21.862499  21.975000  21.030001  21.112499  17.373537  28140800
2010-01-22  21.007500  21.097500  20.410000  20.682501  17.019690  29776400
2010-01-25  20.850000  20.952499  20.352501  20.507500  16.875689  16147200
2010-01-26  20.337500  20.635000  20.247499  20.287500  16.694653  12437600
2010-01-27  20.219999  21.032499  20.152500  20.977501  17.262451  19335200
2010-01-28  21.090000  21.120001  20.352501  20.662500  17.003233  13070800
2010-01-29  20.650000  21.245001  20.467501  20.507500  16.875689  20281600
2010-02-01  20.572500  21.187500  20.549999  20.915001  17.211021  16098000
2010-02-02  21.065001  21.117500  20.875000  21.002501  17.283026  14441600
2010-02-03  21.059999  21.122499  20.525000  20.879999  17.182219  32197600
2010-02-04  21.312500  21.545000  20.700001  20.762501  17.085527  66486800
2010-02-05  20.830000  20.965000  20.135000  20.639999  16.984720  38687200

### Adjustments Excel File Befor Export to PC

In [77]:
del aapl['Adj Close'] #active if you need
aapl.rename(columns={'Volume': 'Volume_BTC'}, inplace=True)
aapl

                  Open        High         Low       Close  Volume_BTC
Date
2009-12-31   21.995001   22.045000   21.792500   21.865000    12643600
2010-01-04   22.000000   22.192499   21.865000   22.035000    20180000
2010-01-05   21.825001   21.882500   21.500000   21.782499    25833600
2010-01-06   21.752501   21.770000   21.475000   21.490000    16254000
2010-01-07   21.492500   21.750000   21.387501   21.690001    27841200
...                ...         ...         ...         ...         ...
2020-04-03  155.559998  157.720001  150.600006  151.850006    11994700
2020-04-06  160.020004  170.729996  158.250000  169.440002    16479100
2020-04-07  177.759995  178.800003  168.100006  168.589996    15379000
2020-04-08  171.009995  176.000000  167.929993  174.940002    11146500
2020-04-09  176.270004  177.190002  172.850006  173.690002    12231800

[2586 rows x 5 columns]

### Export File to PC

In [78]:
#Dont Forget Change file name in folder path
folder_path="D:\Stock Study Excel Files\Input Excel Files\Stock USA\V.xlsx"
aapl.to_excel(folder_path, sheet_name=stock, index=True)
print(f'Ok file Export To ({folder_path})folder' )

Ok file Export To (D:\Stock Study Excel Files\Input Excel Files\Stock USA\V.xlsx)folder

## No5 Stock USA Ta-Lib all features 12-4-2020

In [79]:
import pandas as pd
import ta
import glob
# Import Built-Ins
import logging
# Import Third-Party
# Import Homebrew
import matplotlib.pyplot as plt

plt.style.use('bmh')
# Init Logging Facilities
log = logging.getLogger(__name__)
#################################################################
# 1- Load data
indicators_value = []
ticker_name = []
glob.glob("D:\Stock Study Excel Files\Input Excel Files\Stock USA\*.xlsx")
for f in glob.glob('D:\Stock Study Excel Files\Input Excel Files\Stock USA\*.xlsx'):
    df = pd.read_excel(f)
    # df.columns = map(str.capitalize, df.columns)
    # df.rename(columns={'Volume': 'Volume_BTC'}, inplace=True)
    tike = f.split('\\')[-1].split('.')[0]
    print(tike)
    df.insert(1, 'TICKER', tike)  # to bring excel file name
    # Clean nan values
    df = ta.utils.dropna(df)
    ####################################################################
    # 2-Add all ta features filling nans values (from Ta-Lib Except SuperTrend Because not in Ta-Lib)
    df = ta.add_all_ta_features(df, "Open", "High", "Low", "Close", "Volume_BTC", fillna=True)
    df.round(2).to_excel(f'{f}.xlsx', sheet_name=tike, index=True)

V

C:\Python\lib\site-packages\ta\trend.py:567: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i]/self._trs[i])
C:\Python\lib\site-packages\ta\trend.py:571: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i]/self._trs[i])

In [80]:
df

,Date,TICKER,Open,High,Low,Close,Volume_BTC,volume_adi,volume_obv,volume_cmf,...,momentum_uo,momentum_stoch,momentum_stoch_signal,momentum_wr,momentum_ao,momentum_kama,momentum_roc,others_dr,others_dlr,others_cr
0,2009-12-31,V,21.995001,22.045000,21.792500,21.865000,12643600,-5.382911e+06,12643600,-0.425742,...,50.000000,28.712901,28.712901,-71.287099,0.000000,21.865000,0.000000,-70.790221,0.000000,0.000000
1,2010-01-04,V,22.000000,22.192499,21.865000,22.035000,20180000,-4.612634e+06,32823600,-0.140528,...,50.000000,60.625134,44.669018,-39.374866,0.000000,22.035000,0.000000,0.777499,0.774492,0.777499
2,2010-01-05,V,21.825001,21.882500,21.500000,21.782499,25833600,7.713139e+06,6990000,0.131495,...,50.000000,40.794174,43.377403,-59.205826,0.000000,21.782499,0.000000,-1.145907,-1.152523,-0.377317
3,2010-01-06,V,21.752501,21.770000,21.475000,21.490000,16254000,-6.887979e+06,-9264000,-0.091949,...,50.000000,2.090511,34.503273,-97.909489,0.000000,21.490000,0.000000,-1.342819,-1.351916,-1.715070
4,2010-01-07,V,21.492500,21.750000,21.387501,21.690001,27841200,1.173689e+07,18577200,0.114225,...,50.000000,37.577686,26.820790,-62.422314,0.000000,21.690001,0.000000,0.930669,0.926365,-0.800362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2581,2020-04-03,V,155.559998,157.720001,150.600006,151.850006,11994700,6.119992e+08,1260927600,0.022736,...,47.271030,50.337108,53.827505,-49.662892,-15.660999,171.656012,2.269673,-3.519914,-3.583357,594.488944
2582,2020-04-06,V,160.020004,170.729996,158.250000,169.440002,16479100,6.250715e+08,1277406700,0.083663,...,53.583411,96.494584,70.910192,-3.505416,-14.067823,171.449706,11.290642,11.583797,10.960566,674.937133
2583,2020-04-07,V,177.759995,178.800003,168.100006,168.589996,15379000,6.111010e+08,1262027700,0.005368,...,50.289415,77.245366,74.692352,-22.754634,-11.089204,171.344264,14.819856,-0.501656,-0.502919,671.049614
2584,2020-04-08,V,171.009995,176.000000,167.929993,174.940002,11146500,6.193194e+08,1273174200,0.040719,...,50.879037,91.397371,88.379107,-8.602629,-6.497558,171.467992,28.878735,3.766538,3.697336,700.091490
2585,2020-04-09,V,176.270004,177.190002,172.850006,173.690002,12231800,6.118224e+08,1260942400,0.066187,...,53.065134,88.611546,85.751427,-11.388454,-1.463440,171.496401,12.398889,-0.714531,-0.717096,694.374591

## No7 Stock USA Study 12-4-2020

In [82]:
import pandas as pd
import ta
import glob
# Import Built-Ins
import logging
# Import Third-Party
# Import Homebrew
import matplotlib.pyplot as plt

plt.style.use('bmh')
# Init Logging Facilities
log = logging.getLogger(__name__)
#################################################################
# 1- Load data
indicators_value = []
ticker_name = []
glob.glob("D:\Stock Study Excel Files\Input Excel Files\Stock USA\*.xlsx")
for f in glob.glob('D:\Stock Study Excel Files\Input Excel Files\Stock USA\*.xlsx'):
    df = pd.read_excel(f)
   # df.columns = map(str.capitalize, df.columns)
    #df.rename(columns={'Volume': 'Volume_BTC'}, inplace=True)
    tike = f.split('\\')[-1].split('.')[0]
    print(tike)
    df.insert(1, 'TICKER', tike)  # to bring excel file name
    # Clean nan values
    df = ta.utils.dropna(df)
    ####################################################################
    # 2-Add all ta features filling nans values (from Ta-Lib Except SuperTrend Because not in Ta-Lib)
    df = ta.add_all_ta_features(df, "Open", "High", "Low", "Close", "Volume_BTC", fillna=True)

    #####################################################################
    # 3- Calculate
    df['Signal'] = 0
    sell = []
    buy = []
    date_sell = []
    date_buy = []
    indicators = ['trend_psar']  # The indicators to be studied
    for indicator in indicators:
        # 3.1 Determine the Date of  first buy signal and then exit the loop
        for y in range(10, len(df.index)):
            if df[indicator].iloc[y] <= df['Close'].iloc[y] and (df[indicator].iloc[y - 1] > df['Close'].iloc[y - 1]):
                first_buy_signal = y
                break
        '''
        # 3.2 Beginning of the study of buying and selling signals from the day before the date of the first purchase signal 
        (identified from the previous step) to ensure that the study begins with a buy signal, not selling   '''

        for x in range(first_buy_signal - 1, len(df.index)):
            if df[indicator].iloc[x] >= df['Close'].iloc[x] and (df[indicator].iloc[x - 1] < df['Close'].iloc[x - 1]):
                df['Signal'].iloc[x] = 'Sell'
                sell.append(df['Close'].iloc[x])
                date_sell.append(df['Date'].iloc[x])
            elif df[indicator].iloc[x] <= df['Close'].iloc[x] and (df[indicator].iloc[x - 1] > df['Close'].iloc[x - 1]):
                df['Signal'].iloc[x] = 'Buy'
                buy.append(df['Close'].iloc[x])
                date_buy.append(df['Date'].iloc[x])
        print(len(buy))
        print(len(sell))
        ''' To avoid the presence of a buy signal at the end of operations without the presence of a buy signal, 
        therefore the two columns do not contain the same number and the accounts are stopped '''
        if len(buy) != len(sell):  # To avoid
            del buy[-1]
            del date_buy[-1]
        profits = pd.DataFrame()
        profits['Buy Price'] = buy
        profits['Buy Date'] = date_buy
        profits['Sell Price'] = sell
        profits['Sell Date'] = date_sell
        profits['Profits'] = ((profits['Sell Price'] - profits['Buy Price']) / profits['Buy Price']) * 100
        # profits.drop(profits.tail(1).index, inplace=True)  # drop last n rows
        sum(profits['Profits'])
        profits.round(2).to_excel(f'{f}.xlsx', sheet_name="indicator Osama", index=True, index_label="No.")
        indicators_value.append(sum(profits['Profits']))
    #########################################################################
    tik = df.iloc[0]['TICKER']
    ticker_name.append(tik)
dictionary = dict(zip(ticker_name, indicators_value))
basic = pd.DataFrame(indicators_value, ticker_name)
indicators_na = pd.DataFrame(indicators, index=[0])
final_results = pd.concat([indicators_na, basic], axis=0)
# final_results.insert(0, 'TICKER', tike)
final_results.round(2).to_excel('D:\Stock Study Excel Files\Output Excel Files\Stock USA\indicators.xlsx', sheet_name="indicators value",
                                index=True)

V

C:\Python\lib\site-packages\ta\trend.py:567: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i]/self._trs[i])
C:\Python\lib\site-packages\ta\trend.py:571: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i]/self._trs[i])
C:\Python\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

120
119
            0
0  trend_psar
V      5.0089

In [84]:
profits

      Buy Price   Buy Date  Sell Price  Sell Date   Profits
0     21.962500 2010-01-19   21.112499 2010-01-21 -3.870235
1     20.762501 2010-02-04   20.639999 2010-02-05 -0.590013
2     21.469999 2010-02-16   22.532499 2010-03-18  4.948766
3     22.750000 2010-03-30   23.280001 2010-04-19  2.329673
4     23.785000 2010-04-22   23.402500 2010-04-28 -1.608155
..          ...        ...         ...        ...       ...
114  175.979996 2019-10-04  170.860001 2019-10-22 -2.909419
115  177.850006 2019-10-25  179.889999 2019-11-21  1.147030
116  182.550003 2019-11-26  182.639999 2019-12-12  0.049300
117  185.139999 2019-12-13  201.690002 2020-01-27  8.939183
118  203.940002 2020-02-11  198.789993 2020-02-24 -2.525257

[119 rows x 5 columns]

In [83]:
final_results

            0
0  trend_psar
V      5.0089